CREATE TABLE pedidos (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    data DATETIME DEFAULT CURRENT_TIMESTAMP,
    status ENUM('PENDENTE', 'EM_PREPARO', 'ENTREGUE', 'CANCELADO') NOT NULL,
    cliente_id BIGINT NOT NULL,
    FOREIGN KEY (cliente_id) REFERENCES users(id) ON DELETE CASCADE
);
